'''Each new term in the Fibonacci sequence is
generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence
whose values do not exceed four million, find the
sum of the even-valued terms.'''

def EvenFib(r):
    sums = 2
    fibarray = [1,2]
    for i in range(2,r):
        fib = fibarray[i-1] + fibarray[i-2]
        fibarray = fibarray + [fib]
        if fib%2 == 0:
            sums = sums + fibarray[i]
    return sums,fibarray


def EvenFib2(n):
    a,b=1,2
    sums = 2
    while a<n:
        a,b = b,b+a
        if b%2 == 0:
            sums=sums+b
    return sums

print EvenFib2(10)
print EvenFib2(4000000)

